#!/bin/csh

#PBS -V

### Job name
#PBS -N Experiment1

### Join queuing system output and error files into a single output file
#PBS -j oe

### Send email to user when job ends or aborts
#PBS -m ae

### email address for user
#PBS -M joey.gerlach@ersa.edu.au

### Queue name that job is submitted to
#PBS -q emu

### Request nodes NB THIS IS REQUIRED
#PBS -l nodes=1:ppn=2
#PBS -l mem=2gb
#PBS -l walltime=04:00:00

# This job's working directory
echo Working directory is $PBS_O_WORKDIR
cd $PBS_O_WORKDIR
echo Running on host `hostname`
echo Time is `date`

#Load module(s) if required
module load intel/11.9.293 openmpi/intel64/1.4.3

# Run the executable
mpirun -np 2 hostname

sleep 60

### this is basically the tutorial script from the "how to use tizard" guides
